spring.application.name=thymeleafdemo

countries=Uzbekistan,Tajikistan,Kazakhstan,Turkmenistan,Kyrgyzstan,Afghanistan,China,Russia,USA
languages=Go,Java,Phyton,Rust,Scala,Ruby,C++,Kotlin
systems=MacOs,Linux,Microsoft Windows,Android OS, IOS
