spring.application.name=mybackendapp
# Use wildcard "*" to expose all endpoints
# Can also expose individual endpoints with a comma-delimited list

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# Exclude individual endpoints with a comma-delimited list
# management.endpoints.web.exposure.exclude=health,info

info.app.name=My Backend App
info.app.description=Learning backend development!
info.app.version=1.0.0

#
# Define my backend properties
#
coach.name=Knowledge Base
team.name=Backend Club

#
# Change Spring Boot embedded server port
#
server.port=7070

#
# Set the context path of the application
#
# All requests should be prefixed with /mybackendapp
#
server.servlet.context-path=/mybackendapp