spring.application.name=cruddemo
#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

springdoc.swagger-ui.path=/my-ui.html

springdoc.api-docs.path=/my-api-docs