spring.application.name=mybackendapp
# Use wildcard "*" to expose all endpoints
# Can also expose individual endpoints with a comma-delimited list

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=My Backend App
info.app.description=Learning backend development!
info.app.version=1.0.0
